export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_FAIL = 'USER_LOADING_FAIL';

export const LOADING_START = 'LOADING_START';
export const LOADING_FAIL = 'LOADING_FAIL';

export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const ADD_NEW_BOOK_SUCCESS = 'ADD_NEW_BOOK_SUCCESS';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const ISSUE_BOOK_SUCCESS = 'ISSUE_BOOK_SUCCESS';